# Absolute path to project main folder (on macOS).
# Example: /Users/yourname/Projects/BingWallpaper-Ubuntu
path: /Users/zc/Projects/BingWallpaper-Ubuntu

# mode
# [0]   : today's picture
# [1]   : yesterday's picture
# [2-7] : N days ago
mode: 0
